apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: mikej091/broker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010
